LEGAL_JARGONS = {
    "affidavit": "Written statement confirmed by oath or affirmation, used as legal evidence.",
    "writ": "Formal written order issued by a court directing specific action.",
    "plaintiff": "Person who initiates a lawsuit by filing a complaint in court.",
    "defendant": "Person or entity against whom a lawsuit or criminal charge is brought.",
    "injunction": "Court order requiring a party to do or stop doing something.",
    "habeas corpus": "Legal action to protect individuals against unlawful detention or imprisonment.",
    "jurisdiction": "Legal authority of a court to hear and decide a case.",
    "petition": "Formal written request submitted to a court seeking legal relief.",
    "statute": "Written law enacted by a legislative body and enforced by courts.",
    "precedent": "Past judicial decision that guides courts in deciding similar cases.",
    "litigation": "Process of resolving disputes through the court system.",
    "decree": "Formal order or judgment issued by a court with legal effect.",
    "tribunal": "Special court or body established to decide specific disputes.",
    "subpoena": "Court order requiring a person to appear or present evidence.",
    "amicus curiae": "Friend of the court providing expertise or opinion to assist.",
    "bail": "Temporary release of an accused person awaiting trial, sometimes with money.",
    "testimony": "Formal statement made by a witness under oath in court.",
    "cross-examination": "Questioning of a witness by the opposing party’s lawyer.",
    "verdict": "Formal decision or finding made by a jury or judge.",
    "appeal": "Request to a higher court to review and change a decision.",
    "brief": "Written legal argument submitted to a court outlining case details.",
    "case law": "Law established by judicial decisions rather than statutes.",
    "common law": "Legal system based on customs, precedents, and judicial rulings.",
    "contract": "Legally binding agreement between two or more parties.",
    "damages": "Monetary compensation awarded to a person for loss or injury.",
    "equity": "Branch of law ensuring fairness and justice beyond strict rules.",
    "evidence": "Facts, documents, or testimony presented in court to prove claims.",
    "hearsay": "Secondhand statement presented as evidence, usually inadmissible in court.",
    "indictment": "Formal charge issued by a grand jury accusing someone of crime.",
    "liable": "Legally responsible for actions, damages, or obligations under law.",
    "mens rea": "Mental state or intent required to establish criminal liability.",
    "negligence": "Failure to exercise reasonable care, causing harm to another.",
    "oath": "Formal promise to speak the truth or perform duties faithfully.",
    "plea bargain": "Agreement where defendant pleads guilty for reduced charges or punishment.",
    "probation": "Court-ordered supervision of an offender instead of imprisonment.",
    "remand": "Sending case back to lower court or accused back to custody.",
    "sanction": "Penalty or approval imposed by law or authority.",
    "settlement": "Agreement between parties to resolve a dispute without trial.",
    "statutory": "Defined, regulated, or authorized by legislation or written statutes.",
    "tort": "Civil wrong causing harm, leading to liability for damages.",
    "voir dire": "Jury selection process where potential jurors are questioned for bias.",
    "warranty": "Legal promise or guarantee regarding quality, safety, or performance.",
    "writ of certiorari": "Supreme Court order to review a lower court’s decision.",
    "jurisprudence": "Study, theory, and philosophy of law and legal systems.",
    "alibi": "Defense claiming accused was elsewhere when crime occurred.",
    "burden of proof": "Obligation to prove allegations or claims in a legal case.",
    "contempt of court": "Disrespect or disobedience towards court authority or orders.",
    "discovery": "Pre-trial process where parties exchange evidence and information.",
    "estoppel": "Legal principle preventing a party from contradicting earlier statements.",
    "fiduciary": "Person entrusted with duty to act in another’s best interests.",
    "garnishment": "Court order allowing creditor to collect debt from wages or assets.",
    "immunity": "Protection from prosecution or legal liability under certain conditions.",
    "injunctive relief": "Court-ordered action stopping or requiring specific conduct to prevent harm.",
    "lien": "Legal claim on another’s property until a debt is paid.",
    "malfeasance": "Wrongful, illegal, or dishonest conduct by a public official.",
    "nolo contendere": "Plea meaning 'no contest,' not admitting guilt but accepting punishment.",
    "prima facie": "Case strong enough to be proven unless rebutted by evidence.",
    "res judicata": "Principle preventing re-litigation of a case already finally decided.",
    "subrogation": "Right of one party to claim damages on another’s behalf.",
    "trustee": "Individual/entity managing property or assets for another’s benefit.",
    "ultra vires": "Act performed beyond the legal power or authority granted.",
    "venue": "Geographic location where a legal case is heard or tried.",
    "waiver": "Voluntary relinquishment of a known legal right or claim.",
    "accord and satisfaction": "Agreement resolving a dispute by accepting different performance than originally agreed.",
    "acquittal": "Court judgment declaring the accused not guilty of criminal charges.",
    "adjournment": "Postponement or suspension of court proceedings to a later time.",
    "admissible evidence": "Evidence allowed to be presented in court under legal rules.",
    "allegation": "Statement or claim made in legal proceedings without proof yet.",
    "arbitration": "Alternative dispute resolution where neutral third party decides the case.",
    "arraignment": "Formal reading of criminal charges where accused enters a plea.",
    "breach of contract": "Failure to fulfill obligations under a valid legal contract.",
    "capital punishment": "Legal penalty of death for certain serious criminal offenses.",
    "cause of action": "Legal grounds or facts giving rise to the right to sue.",
    "class action": "Lawsuit filed by one person on behalf of a large group.",
    "codicil": "Legal document amending or supplementing an existing will.",
    "collateral": "Property pledged as security for repayment of a loan or obligation.",
    "concurrent sentence": "Prison sentences served simultaneously for multiple offenses.",
    "confession": "Voluntary statement admitting involvement or guilt in a crime.",
    "consideration": "Something of value exchanged to form a valid legal contract.",
    "conviction": "Formal declaration of guilt by a judge or jury in criminal case.",
    "custody": "Legal right or duty to care for and control a person or property.",
    "default judgment": "Court decision made against a party failing to respond or appear.",
    "defamation": "False statement harming another’s reputation, spoken or written.",
    "disbarment": "Legal removal of a lawyer’s license to practice law.",
    "duress": "Coercion or pressure forcing someone to act against free will.",
    "embezzlement": "Fraudulent misappropriation of money/property entrusted to one’s care.",
    "entrapment": "Law enforcement inducing someone to commit a crime they otherwise wouldn’t.",
    "expungement": "Legal process of erasing or sealing criminal records from public view.",
    "felony": "Serious criminal offense punishable by imprisonment exceeding one year or death.",
    "forgery": "Fraudulent making or altering of a document with intent to deceive.",
    "grand jury": "Panel of citizens deciding if enough evidence exists to indict.",
    "hearing": "Formal court session for argument, testimony, or evidence presentation.",
    "impeachment": "Process of charging and possibly removing a public official for misconduct.",
    "incarceration": "Confinement in prison as punishment for a crime.",
    "intestate": "Condition of dying without leaving a valid legal will.",
    "malpractice": "Professional negligence causing harm, often in medicine or law.",
    "misdemeanor": "Less serious crime punishable by fines or short-term imprisonment.",
    "mistrial": "Invalid trial due to error, misconduct, or hung jury.",
    "mitigating circumstances": "Factors reducing severity or culpability of an offense.",
    "parole": "Conditional release of prisoner before completion of full sentence.",
    "perjury": "Lying under oath in judicial proceedings.",
    "plea": "Formal statement by defendant admitting or denying criminal charges.",
    "probate": "Legal process validating a will and administering estate distribution.",
    "prosecution": "Government’s legal action against someone accused of crime.",
    "restitution": "Compensation ordered to be paid to victim for loss or damage.",
    "search warrant": "Court authorization to search property for evidence of crime.",
    "severance": "Separation of lawsuits or defendants for individual trial handling.",
    "statute of limitations": "Time limit within which legal action must be initiated.",
    "double jeopardy": "Prohibition against being tried twice for same crime.",
    "due process": "Fair legal procedures guaranteed by law and constitution.",
    "eminent domain": "Government’s right to take private property for public use with compensation.",
    "extradition": "Surrender of person by one jurisdiction to another for trial.",
    "fraud": "Intentional deception causing harm or unfair advantage.",
    "guardian ad litem": "Court-appointed representative for child or incapacitated person in case.",
    "hostile witness": "Witness who is antagonistic or adverse to questioning party.",
    "juror": "Member of jury chosen to decide case outcome.",
    "lawsuit": "Legal action brought by one party against another for remedy.",
    "appeal court": "Higher court reviewing decisions of lower courts.",
    "breach": "Violation of law, duty, or contract terms.",
    "citation": "Official order to appear in court or pay fine.",
    "default": "Failure to fulfill legal duty, often in contracts or payments.",
    "dismissal": "Termination of a case without further hearing or trial.",
    "dispute": "Legal disagreement between two or more parties.",
    "grievance": "Formal complaint raised about injustice or unfair treatment.",
    "injury": "Harm or loss suffered, physical, mental, or financial.",
    "lease": "Contract giving right to use property for specific time.",
    "liquidation": "Process of closing a business and selling its assets.",
    "mortgage": "Loan agreement where property is pledged as security.",
    "parliament": "Legislative body responsible for making laws in a country.",
    "summons": "Official notice requiring someone to appear in court.",
    "verbal agreement": "Oral contract made without written documentation."
}
